# **Day 5 - Data Cleaning and preprocessing**

In [ ]:

!pip install kagglehub pandas -q

import os
import kagglehub
import pandas as pd

dir = kagglehub.dataset_download("marvyaymanhalim/student-performance-and-attendance-dataset")

file_path = os.path.join(dir, "attendance.csv")
df = pd.read_csv(file_path)

Downloading to /root/.cache/kagglehub/datasets/marvyaymanhalim/student-performance-and-attendance-dataset/1.archive...

100%|██████████| 5.58M/5.58M [00:01<00:00, 4.16MB/s]

Extracting files...

In [ ]:
display(df.head())

  Student_ID        Date    Subject Attendance_Status
0     S06592  2024-09-20     Arabic           Present
1     S01777  2025-01-22       Math           Present
2     S07362  2024-12-03  Geography          PRESENT
3     S12119  2024-03-16  Geography           excused
4     S02002  2024-05-24       Math          PRESENT

In [ ]:
display(df.tail())

       Student_ID        Date  Subject Attendance_Status
364675     S08595  2025-02-14     Math           Present
364676     S11222  2025-03-06  Science        left early
364677     S11344  2024-04-18  History           Present
364678     S04381  2024-10-04  Science          PRESENT
364679     S12134  2024-09-19  English           excused

In [ ]:
num_rows, num_cols = df.shape
print(f"Total number of rows: {num_rows}")
print(f"Total number of columns: {num_cols}")

Total number of rows: 364680
Total number of columns: 4

In [ ]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 364680 entries, 0 to 364679
Data columns (total 4 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Student_ID         364680 non-null  object
 1   Date               364680 non-null  object
 2   Subject            364680 non-null  object
 3   Attendance_Status  364680 non-null  object
dtypes: object(4)
memory usage: 11.1+ MB

None

In [ ]:
df.isnull()

        Student_ID   Date  Subject  Attendance_Status
0            False  False    False              False
1            False  False    False              False
2            False  False    False              False
3            False  False    False              False
4            False  False    False              False
...            ...    ...      ...                ...
364675       False  False    False              False
364676       False  False    False              False
364677       False  False    False              False
364678       False  False    False              False
364679       False  False    False              False

[364680 rows x 4 columns]

In [ ]:
df.isnull().count()

Student_ID           364680
Date                 364680
Subject              364680
Attendance_Status    364680
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(290)

In [ ]:
dup=df.drop_duplicates()
dup

       Student_ID        Date    Subject Attendance_Status
0          S06592  2024-09-20     Arabic           Present
1          S01777  2025-01-22       Math           Present
2          S07362  2024-12-03  Geography          PRESENT
3          S12119  2024-03-16  Geography           excused
4          S02002  2024-05-24       Math          PRESENT
...           ...         ...        ...               ...
364675     S08595  2025-02-14       Math           Present
364676     S11222  2025-03-06    Science        left early
364677     S11344  2024-04-18    History           Present
364678     S04381  2024-10-04    Science          PRESENT
364679     S12134  2024-09-19    English           excused

[364390 rows x 4 columns]

In [ ]:
df.duplicated().sum()

np.int64(290)

In [ ]:
df

       Student_ID        Date    Subject Attendance_Status
0          S06592  2024-09-20     Arabic           Present
1          S01777  2025-01-22       Math           Present
2          S07362  2024-12-03  Geography          PRESENT
3          S12119  2024-03-16  Geography           excused
4          S02002  2024-05-24       Math          PRESENT
...           ...         ...        ...               ...
364675     S08595  2025-02-14       Math           Present
364676     S11222  2025-03-06    Science        left early
364677     S11344  2024-04-18    History           Present
364678     S04381  2024-10-04    Science          PRESENT
364679     S12134  2024-09-19    English           excused

[364390 rows x 4 columns]

In [ ]:
dup1=df.duplicated().sum()
print(dup1)

0

In [ ]:
df.drop_duplicates(inplace=True)
print(f"DataFrame after dropping duplicates: {df.shape[0]} rows, {df.shape[1]} columns")

DataFrame after dropping duplicates: 364390 rows, 4 columns

In [ ]:
duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows after dropping: {duplicate_count}")

Number of duplicate rows after dropping: 0

In [ ]:
df

       Student_ID        Date    Subject Attendance_Status
0          S06592  2024-09-20     Arabic           Present
1          S01777  2025-01-22       Math           Present
2          S07362  2024-12-03  Geography          PRESENT
3          S12119  2024-03-16  Geography           excused
4          S02002  2024-05-24       Math          PRESENT
...           ...         ...        ...               ...
364675     S08595  2025-02-14       Math           Present
364676     S11222  2025-03-06    Science        left early
364677     S11344  2024-04-18    History           Present
364678     S04381  2024-10-04    Science          PRESENT
364679     S12134  2024-09-19    English           excused

[364390 rows x 4 columns]

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 364390 entries, 0 to 364679
Data columns (total 4 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Student_ID         364390 non-null  object
 1   Date               364390 non-null  datetime64[ns]
 2   Subject            364390 non-null  object
 3   Attendance_Status  364390 non-null  object
dtypes: datetime64[ns](1), object(3)
memory usage: 13.9+ MB

In [8]:
import pandas as pd
import os
import kagglehub

dir = kagglehub.dataset_download("marvyaymanhalim/student-performance-and-attendance-dataset")
file_path = os.path.join(dir, "attendance.csv")
df = pd.read_csv(file_path)
df.drop_duplicates(inplace=True)
df['Date'] = pd.to_datetime(df['Date'])
df.columns = df.columns.str.lower()
df.info()

Downloading to /root/.cache/kagglehub/datasets/marvyaymanhalim/student-performance-and-attendance-dataset/1.archive...

100%|██████████| 5.58M/5.58M [00:01<00:00, 4.09MB/s]

Extracting files...

<class 'pandas.core.frame.DataFrame'>
Index: 364390 entries, 0 to 364679
Data columns (total 4 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   student_id         364390 non-null  object
 1   date               364390 non-null  datetime64[ns]
 2   subject            364390 non-null  object
 3   attendance_status  364390 non-null  object
dtypes: datetime64[ns](1), object(3)
memory usage: 13.9+ MB

In [9]:
df['attendance_status'] = df['attendance_status'].str.strip().str.upper()
df['attendance_status'].value_counts()

attendance_status
PRESENT       91555
LATE          90935
ABSENT        45711
ABSNT         45435
LEFT EARLY    45400
EXCUSED       45354
Name: count, dtype: int64

In [10]:
df_sorted = df.sort_values(by='date')
df_sorted.head()

       student_id       date    subject attendance_status
11907      S04585 2024-03-09    Science              LATE
219032     S01204 2024-03-09    History              LATE
156452     S11007 2024-03-09     Arabic           EXCUSED
176622     S02591 2024-03-09  Geography           PRESENT
81221      S12052 2024-03-09     Arabic            ABSENT

In [28]:
df['attendance_status'] = df['attendance_status'].replace('ABSNT', 'ABSENT')
df['attendance_status'].value_counts()

attendance_status
PRESENT       91555
ABSENT        91146
LATE          90935
LEFT EARLY    45400
EXCUSED       45354
Name: count, dtype: int64

In [29]:
df['status_code'] = (df['attendance_status'] == 'PRESENT').astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 364390 entries, 0 to 364679
Data columns (total 5 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   student_id         364390 non-null  object
 1   date               364390 non-null  datetime64[ns]
 2   subject            364390 non-null  object
 3   attendance_status  364390 non-null  object
 4   status_code        364390 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 16.7+ MB

In [30]:
present_students = df[df['attendance_status'] == 'PRESENT']
present_students.head()

   student_id       date    subject attendance_status  status_code
0      S06592 2024-09-20     Arabic           PRESENT            1
1      S01777 2025-01-22       Math           PRESENT            1
2      S07362 2024-12-03  Geography           PRESENT            1
4      S02002 2024-05-24       Math           PRESENT            1
14     S02096 2025-01-01       Math           PRESENT            1

In [31]:
df_encoded = pd.get_dummies(df, columns=['subject'])
df_encoded.head()

,student_id,date,attendance_status,status_code,subject_Arabic,subject_English,subject_Geography,subject_History,subject_Math,subject_Science
0,S06592,2024-09-20,PRESENT,1,True,False,False,False,False,False
1,S01777,2025-01-22,PRESENT,1,False,False,False,False,True,False
2,S07362,2024-12-03,PRESENT,1,False,False,True,False,False,False
3,S12119,2024-03-16,EXCUSED,0,False,False,True,False,False,False
4,S02002,2024-05-24,PRESENT,1,False,False,False,False,True,False

In [11]:
import pandas as pd
import os
import kagglehub

dir = kagglehub.dataset_download("marvyaymanhalim/student-performance-and-attendance-dataset")
file_path = os.path.join(dir, "attendance.csv")
df = pd.read_csv(file_path)
df.drop_duplicates(inplace=True)
df['Date'] = pd.to_datetime(df['Date'])
df.columns = df.columns.str.lower()
df.info()

Using Colab cache for faster access to the 'student-performance-and-attendance-dataset' dataset.
<class 'pandas.core.frame.DataFrame'>
Index: 364390 entries, 0 to 364679
Data columns (total 4 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   student_id         364390 non-null  object
 1   date               364390 non-null  datetime64[ns]
 2   subject            364390 non-null  object
 3   attendance_status  364390 non-null  object
dtypes: datetime64[ns](1), object(3)
memory usage: 13.9+ MB

In [12]:
df['attendance_status'] = df['attendance_status'].str.strip().str.upper()
df['attendance_status'].value_counts()

attendance_status
PRESENT       91555
LATE          90935
ABSENT        45711
ABSNT         45435
LEFT EARLY    45400
EXCUSED       45354
Name: count, dtype: int64

In [13]:
df_sorted = df.sort_values(by='date')
df_sorted.head()

       student_id       date    subject attendance_status
11907      S04585 2024-03-09    Science              LATE
219032     S01204 2024-03-09    History              LATE
156452     S11007 2024-03-09     Arabic           EXCUSED
176622     S02591 2024-03-09  Geography           PRESENT
81221      S12052 2024-03-09     Arabic            ABSENT

In [14]:
import pandas as pd
import os
import kagglehub

dir = kagglehub.dataset_download("marvyaymanhalim/student-performance-and-attendance-dataset")
file_path = os.path.join(dir, "attendance.csv")
df = pd.read_csv(file_path)
df.drop_duplicates(inplace=True)
df['Date'] = pd.to_datetime(df['Date'])
df.columns = df.columns.str.lower()
df.info()

Using Colab cache for faster access to the 'student-performance-and-attendance-dataset' dataset.
<class 'pandas.core.frame.DataFrame'>
Index: 364390 entries, 0 to 364679
Data columns (total 4 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   student_id         364390 non-null  object
 1   date               364390 non-null  datetime64[ns]
 2   subject            364390 non-null  object
 3   attendance_status  364390 non-null  object
dtypes: datetime64[ns](1), object(3)
memory usage: 13.9+ MB

In [15]:
df.columns = df.columns.str.lower()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 364390 entries, 0 to 364679
Data columns (total 4 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   student_id         364390 non-null  object
 1   date               364390 non-null  datetime64[ns]
 2   subject            364390 non-null  object
 3   attendance_status  364390 non-null  object
dtypes: datetime64[ns](1), object(3)
memory usage: 13.9+ MB

In [16]:
df['attendance_status'] = df['attendance_status'].str.strip().str.upper()
df['attendance_status'].value_counts()

attendance_status
PRESENT       91555
LATE          90935
ABSENT        45711
ABSNT         45435
LEFT EARLY    45400
EXCUSED       45354
Name: count, dtype: int64

In [17]:
df['status_code'] = (df['attendance_status'] == 'PRESENT').astype(int)
df.head()

  student_id       date    subject attendance_status  status_code
0     S06592 2024-09-20     Arabic           PRESENT            1
1     S01777 2025-01-22       Math           PRESENT            1
2     S07362 2024-12-03  Geography           PRESENT            1
3     S12119 2024-03-16  Geography           EXCUSED            0
4     S02002 2024-05-24       Math           PRESENT            1

In [18]:
present_students = df[df['attendance_status'] == 'PRESENT']
present_students.head()

   student_id       date    subject attendance_status  status_code
0      S06592 2024-09-20     Arabic           PRESENT            1
1      S01777 2025-01-22       Math           PRESENT            1
2      S07362 2024-12-03  Geography           PRESENT            1
4      S02002 2024-05-24       Math           PRESENT            1
14     S02096 2025-01-01       Math           PRESENT            1

In [19]:
df_encoded = pd.get_dummies(df, columns=['subject'])
df_encoded.head()

,student_id,date,attendance_status,status_code,subject_Arabic,subject_English,subject_Geography,subject_History,subject_Math,subject_Science
0,S06592,2024-09-20,PRESENT,1,True,False,False,False,False,False
1,S01777,2025-01-22,PRESENT,1,False,False,False,False,True,False
2,S07362,2024-12-03,PRESENT,1,False,False,True,False,False,False
3,S12119,2024-03-16,EXCUSED,0,False,False,True,False,False,False
4,S02002,2024-05-24,PRESENT,1,False,False,False,False,True,False

In [20]:
df_sorted = df.sort_values(by='date')
df_sorted.head()

       student_id       date    subject attendance_status  status_code
11907      S04585 2024-03-09    Science              LATE            0
219032     S01204 2024-03-09    History              LATE            0
156452     S11007 2024-03-09     Arabic           EXCUSED            0
176622     S02591 2024-03-09  Geography           PRESENT            1
81221      S12052 2024-03-09     Arabic            ABSENT            0

In [21]:
import pandas as pd
df.columns = df.columns.str.lower()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 364390 entries, 0 to 364679
Data columns (total 5 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   student_id         364390 non-null  object
 1   date               364390 non-null  datetime64[ns]
 2   subject            364390 non-null  object
 3   attendance_status  364390 non-null  object
 4   status_code        364390 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 16.7+ MB

In [22]:
df['attendance_status'] = df['attendance_status'].str.strip().str.upper()
df['attendance_status'].value_counts()

attendance_status
PRESENT       91555
LATE          90935
ABSENT        45711
ABSNT         45435
LEFT EARLY    45400
EXCUSED       45354
Name: count, dtype: int64

In [23]:
df['status_code'] = (df['attendance_status'] == 'PRESENT').astype(int)
df.head()

  student_id       date    subject attendance_status  status_code
0     S06592 2024-09-20     Arabic           PRESENT            1
1     S01777 2025-01-22       Math           PRESENT            1
2     S07362 2024-12-03  Geography           PRESENT            1
3     S12119 2024-03-16  Geography           EXCUSED            0
4     S02002 2024-05-24       Math           PRESENT            1

In [24]:
present_students = df[df['attendance_status'] == 'PRESENT']
present_students.head()

   student_id       date    subject attendance_status  status_code
0      S06592 2024-09-20     Arabic           PRESENT            1
1      S01777 2025-01-22       Math           PRESENT            1
2      S07362 2024-12-03  Geography           PRESENT            1
4      S02002 2024-05-24       Math           PRESENT            1
14     S02096 2025-01-01       Math           PRESENT            1

In [25]:
df_encoded = pd.get_dummies(df, columns=['subject'])
df_encoded.head()

,student_id,date,attendance_status,status_code,subject_Arabic,subject_English,subject_Geography,subject_History,subject_Math,subject_Science
0,S06592,2024-09-20,PRESENT,1,True,False,False,False,False,False
1,S01777,2025-01-22,PRESENT,1,False,False,False,False,True,False
2,S07362,2024-12-03,PRESENT,1,False,False,True,False,False,False
3,S12119,2024-03-16,EXCUSED,0,False,False,True,False,False,False
4,S02002,2024-05-24,PRESENT,1,False,False,False,False,True,False

In [26]:
df_sorted = df.sort_values(by='date')
df_sorted.head()

       student_id       date    subject attendance_status  status_code
11907      S04585 2024-03-09    Science              LATE            0
219032     S01204 2024-03-09    History              LATE            0
156452     S11007 2024-03-09     Arabic           EXCUSED            0
176622     S02591 2024-03-09  Geography           PRESENT            1
81221      S12052 2024-03-09     Arabic            ABSENT            0

In [33]:
df['subject'] = df['subject'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 364390 entries, 0 to 364679
Data columns (total 5 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   student_id         364390 non-null  object
 1   date               364390 non-null  datetime64[ns]
 2   subject            364390 non-null  object
 3   attendance_status  364390 non-null  object
 4   status_code        364390 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 16.7+ MB